# Generated by Django 3.0.8 on 2020-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='make',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
